<?php

/**
 * @file
 * Negnet Utility Module.
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_preprocess_field().
 */
function negnet_utility_preprocess_field(&$variables, $hook) {
  // Hide al labels.
  $variables['label_display'] = 'hidden';
  $variables['label_hidden'] = TRUE;
}

/**
 * Implements hook_preproces_image().
 */
function negnet_utility_preprocess_image(&$variables) {
  if (isset($variables['attributes']['srcset'])) {
    // This is a responsive image
    // apply lazyload.
    $variables['attributes']['data-srcset'] = $variables['attributes']['srcset'];
    $variables['attributes']['class'][] = 'lazyload';
    $variables['attributes']['class'][] = 'responsive-image';
    unset($variables['attributes']['srcset']);
    $variables['#attached']['library'][] = 'negnet_utility/negnet-responsive-images';
  }
}

/**
 * Implements hook_preprocess_responsive_image().
 */
function negnet_utility_preprocess_responsive_image(&$variables) {
  // Add base height and width as data elements.
  if (isset($variables['height']) && isset($variables['width'])) {
    $variables['img_element']['#attributes']['data-width'] = $variables['width'];
    $variables['img_element']['#attributes']['data-height'] = $variables['height'];
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function negnet_utility_form_user_login_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  // Alter login form and add own custom submit handler.
  $form['#submit'][] = '_negnet_utility_user_login_form_submit';
}

/**
 * Custom submit handler for login form.
 */
function _negnet_utility_user_login_form_submit($form, FormStateInterface $form_state) {
  // Set redirect to login form.
  $form_state->setRedirect('<front>');
}
