<?php

/**
 * @file
 * Negnet Utility Module.
 */

/**
 * Implements hook_preprocess_field().
 */
function negnet_utility_preprocess_field(&$variables, $hook) {
  // Hide al labels.
  $variables['label_display'] = 'hidden';
  $variables['label_hidden'] = TRUE;
}

/**
 * Implements hook_preproces_image().
 */
function negnet_utility_preprocess_image(&$variables) {
  if (isset($variables['attributes']['srcset'])) {
    // This is a responsive image
    // apply lazyload.
    $variables['attributes']['data-srcset'] = $variables['attributes']['srcset'];
    $variables['attributes']['class'][] = 'lazyload';
    $variables['attributes']['class'][] = 'responsive-image';
    unset($variables['attributes']['srcset']);
    $variables['#attached']['library'][] = 'negnet_utility/negnet-responsive-images';
  }
}
